export default {
    HOST: 'https://localhost',
    PORT: 3001,
    APP_INTERNAL_KEY: 'atlas',
    APP_NAME_PRETTY: 'Atlas - Help Center',
    APP_APSTORE_URL: 'http://google.com',
    MONGO_URI: 'mongodb://localhost:27017/atlas',
    SHOPIFY_API_KEY: 'your_key',
    SHOPIFY_API_SECRET: 'your_secret',
    SHOP_ACCESS_SCOPES: ['read_script_tags', 'write_script_tags'],
    SESSION_SECRET: 'session_secret',
    BILLING: {
        PACKAGES: {
            starter_plan: {
                name: 'Standard',
                price: 7,
                description: 'Standard plan',
            },
        },
        TRIAL_DAYS: 14,
        PLACE_CHARGE_AT_INSTALL: true,
        TEST_CHARGE_SHOPS: ['your_shop.myshopify.com'],
        MANDATORY_PAYMENT_ON_INSTALL: 'starter_plan', // can also be false
    },
    AWS_ACCESS_KEY: 'your_key',
    AWS_SECRET: 'your_secret',
    AWS_REGION: 'eu-west-1',
    AWS_API_VERSION: '2006-03-01',
    AWS_S3_BUCKET_URL: 'https://s3-eu-west-1.amazonaws.com/bucket_name',
    AWS_S3_BUCKET_NAME: 'bucket_name',
    AWS_S3_OTHER_APPS_JSON: 'https://s3-eu-west-1.amazonaws.com/other-apps.json',
    AWS_CLOUDWATCH_LOGS_GROUPNAME: 'your_log_group',
    PLACE_SCRIP_TAG_ON_INSTALL: false,
    SEND_WELCOME_EMAIL: true,
    SENDGRID_API_KEY: 'you_api_key',
    SENDGRID_WELCOME_TEMPLATE_ID: 'template_id',
    SENDGRID_WELCOME_FROM_EMAIL: 'hello@yourdomain.com',
    SENDGRID_WELCOME_SUBJECT: 'Welcome to Atlas - Help Center',
    SENDGRID_SUPPORT_EMAIL: 'hello@yourdomain.com',
    SLACK_WEBHOOK_URI: 'https://hooks.slack.com/services/your_url',
    SLACK_MAIN_CHANNEL: '#main_channel',
    JWT_SECRET: 'jwt_secret',
    MAX_STORAGE_SPACE: 1000000 * 1000 * 2, // 1MB * 1000 * 2 = 2GB
    MAX_CATEGORIES: 500,
    MAX_ARTICLES: 2000,
    MAX_CATEGORIES_PAGE: 10,
    MAX_ARTICLES_PAGE: 10,
    PERKS: [
        {
            type: 'trial', code: 'CARSON90DAYS', days: 90, expiresAt: '2040-05-20',
            description: `90 Days Free Trial Period - Courtesy of <a href="https://someone.com" target="_blank">someone</a>.`,
        },
    ],
};
